### PR TITLE
Implements [Feature Request] CustomPaint for drawPath #31

### LINKED ISSUE #31: [Feature Request] CustomPaint for drawPath
ATM paint is hardcoded and there is no way for user to set paint style for `drawPath`.

### PR DESCRIPTION
**Pull request by sikandernoori**
fixes #31

### CODE REVIEW

**Comment by sikandernoori** [comment]
@ikbendewilliam can you please check this PR.

**Comment by ikbendewilliam** [comment]
Thank you for your PR!
Code looks good, can you add a description in the readme for the argument? The same one as you've written in the code is good

**Comment by sikandernoori** [comment]
> Thank you for your PR! Code looks good, can you add a description in the readme for the argument? The same one as you've written in the code is good

Done.

**Review by ikbendewilliam — APPROVED** [review]

**Comment by ikbendewilliam** [comment]
Your formatting seems to have failed. Please run `dart format .` (might also be my mistake in a previous push, but if you run this it should be fixed)

**Comment by sikandernoori** [comment]
> Your formatting seems to have failed. Please run `dart format .` (might also be my mistake in a previous push, but if you run this it should be fixed)

Just did. Could it be due to the commented code ?

That I kept as an example for users.

```
flutter-custom-image-crop % dart format .
Formatted 18 files (0 changed) in 0.20 seconds.
```

**Comment by sikandernoori** [comment]
> Your formatting seems to have failed. Please run `dart format .` (might also be my mistake in a previous push, but if you run this it should be fixed)

Done.

**Comment by ikbendewilliam** [comment]
Ah so it was my bad. Apologies

**Comment by ikbendewilliam** [comment]
Release in progress. New version is 0.0.8

**Pull request merged**
